### PR TITLE
Add openstreetmap attribution

### PR DESCRIPTION
**Pull request by yurukov**
Also, the email address needs to be changed.

### CODE REVIEW

**Comment by mitio** [comment]
Thanks! 🙇

**Comment by mitio** [comment]
BTW, which email address needs to be changed?

**Comment by yurukov** [comment]
Адресът, на който се изпращат промените. В кода сега е example@mail.com и
никой не може да предложи промяна на мястото на училище.

б.

On Tue, May 10, 2016 at 2:28 PM, Dimitar Dimitrov notifications@github.com
wrote:

> BTW, which email address needs to be changed?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/governmentbg/data-viz/pull/1#issuecomment-218142372

## 

---

Boyan Yurukov
Twitter: yurukov
http://yurukov.net/blog

**Comment by mitio** [comment]
Благодаря, оправено е вече.

**Pull request merged**
